demo2/demo2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('polls/',include('polls.urls',namespace='polls')),
]

demo2/polls/urls.py
from django.conf.urls import url
from . import views
app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^vote/$',views.vote, name='vote'),
    url(r'^result/(\d+)/$',views.result,name='result')
]

demo2/polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=50)
    pub_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.question_text

class Choices(models.Model):
    question = models.ForeignKey("Question", on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=20)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

demo2/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import Question,Choices
# Create your views here.

def index(request):
    # return HttpResponse("首页")
    questions = Question.objects.all()
    return render(request,'polls/index.html',{"questions":questions})

def detail(request,id):
    question = Question.objects.get(pk=id)
    return render(request,'polls/detail.html',{"question":question})

def vote(request):
    id = request.POST["votenum"]
    choice = Choices.objects.get(pk=id)
    choice.votes += 1
    choice.save()
    # return HttpResponse("投票完成")
    return HttpResponseRedirect('/polls/result/'+str(choice.id)+'/')

def result(request,cid):
    # return HttpResponse("hello")
    choice = Choices.objects.get(pk=cid)
    return render(request,'polls/result.html',{"question":choice.question})

demo2/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
</head>
<body>
    <div class="container">
        <h2>投票信息：{{question.question_text}}</h2>

        <ul>
            <h3>投票选项</h3>
            <form action="{% url 'polls:vote'%}" method="post">
                {% for choice in  question.choices_set.all %}
                    {% if forloop.counter == 1 %}
                    <li><input type="radio" name="votenum" value="{{choice.id}}" checked>  {{choice.choice_text}}</li>
                    {% else %}
                    <li><input type="radio" name="votenum" value="{{choice.id}}">  {{choice.choice_text}}</li>
                    {% endif %}
                {% empty %}
                    <h4>没有可选项目</h4>
                {% endfor %}
                <input type="submit" value="投票">
            </form>

        </ul>
        <p><a href="/polls/">返回</a></p>
    </div>
</body>
</html>

demo2/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css'%}">

</head>
<body>
    <div class="container">
        <h2>投票信息汇总</h2>
        <ul>
            {% for question in questions %}
                <li><a href="{% url 'polls:detail' question.id %}">{{forloop.counter}}.{{question.question_text}}</a></li>
            {% empty %}
                <h4>没有投票信息</h4>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

demo2/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票结果</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
</head>
<body>
    <div class="container">
        <h2>投票信息：{{question.question_text}}</h2>
        <ul>
            <h3>当前得票信息</h3>
            {% for choice in question.choices_set.all%}
            <li> {{choice.choice_text}}  票数: {{choice.votes}} </li>
            {% empty %}
            <h4>没有票数信息</h4>
            {% endfor %}
        </ul>
    <p><a href="/polls/">返回</a></p>
    </div>
</body>
</html>