demo4/booklibrary/urls.py
from django.conf.urls import url
from . import views
app_name = 'booklibrary'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^readerlogin/$',views.readerlogin,name='readerlogin'),
    url(r'^readerregister/$',views.readerregister,name='readerregister'),
    url(r'^reader/$',views.reader,name='reader'),
    url(r'^readerlogout/$',views.readerlogout,name='readerlogout'),
    url(r'^readerquery/$', views.readerquery, name='readerquery'),
    url(r'^reader/book/(\d+)/$',views.book,name='book'),
    url(r'^reader/info/$',views.readerinfo,name='readerinfo'),
    url(r'^reader/modify/$',views.readermodify,name='readermodify'),
    url(r'^reader/history/$',views.readerhistory,name='readerhistory'),


    url(r'^upload/$', views.upload,name='upload'),

    # 富文本编辑器
    url(r'^edit/$', views.edit,name='edit'),

    url(r'^mail/$',views.mail,name='mail'),

    url(r'^active/(.*?)/$',views.active, name='active'),

    url(r'^ajax/$', views.ajax, name='ajax'),

    url(r'^ajaxajax/$', views.ajaxajax, name='ajaxajax'),

    url(r'^ajaxlogin/$',views.ajaxlogin,name='ajaxlogin'),
    url(r'^checkuser/$',views.checkuser,name='checkuser'),

    url(r'^verifycode/$',views.verifycode,name='verifycode'),
    url(r'^echarts/$',views.echarts,name='echarts'),

]

demo4/demo4/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('booklibrary/',include('booklibrary.urls',namespace='booklibrary')),
]

demo4/booklibrary/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class StudentUser(User):
    college = models.CharField(max_length=20,blank=True,null=True)
    num = models.IntegerField(blank=True,null=True)

class Book(models.Model):
    name = models.CharField(max_length=20)
    author = models.CharField(max_length=20,blank=True,null=True)
    publish_com = models.CharField(max_length=20,null=True,blank=True)
    publish_date = models.DateTimeField(null=True,blank=True)

    def __str__(self):
        return self.name

class History(models.Model):
    book = models.ForeignKey(Book,on_delete=models.CASCADE)
    studentuser = models.ForeignKey(StudentUser,on_delete=models.CASCADE)
    date_borrow = models.DateTimeField(auto_now_add=True)
    date_return = models.DateTimeField()
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.studentuser.username + '  借   <<' +self.book.name + ">>"

class HotPic(models.Model):
    index = models.IntegerField()
    pic = models.ImageField(upload_to='hotpic/')

    def __str__(self):
        return self.pic.name

from tinymce.models import HTMLField
class MessageInfo(models.Model):
    title = models.CharField(max_length=20)
    # HTML 富文本字段
    message = HTMLField()
    def __str__(self):
        return self.title

demo4/booklibrary/views.py
from django.shortcuts import render,redirect,reverse,get_object_or_404
from django.http import HttpResponse
from .models import StudentUser,Book,History,HotPic,MessageInfo
from django.db.models import Q
from datetime import datetime,timedelta
from django.core.mail import send_mail,send_mass_mail
from django.conf import settings
# Create your views here.
import random
import io
from PIL import Image,ImageDraw,ImageFont
import time
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer,BadSignature,SignatureExpired
from django.views.decorators.cache import cache_page
from django.core.cache import cache
# 缓存页面
@cache_page(60*15)
def index(request):

    # 底层缓存API
    reuslt = cache.get("code1")
    print(reuslt)
    reuslt = cache.set("code1","12345")
    print(reuslt)
    reuslt = cache.get("code1")
    print(reuslt)




    messageinfos = MessageInfo.objects.all()
    return render(request,'booklibrary/index.html',{"messageinfos":messageinfos})

def readerlogin(request):
    if request.method == "GET":
        return render(request,'booklibrary/reader_login.html')
    else:
        error = None
        un = request.POST.get("username")
        pwd = request.POST.get("password")
        try:
            user = StudentUser.objects.get(username = un)
            if user.check_password(pwd):
                request.session["username"] = un
                return redirect(reverse('booklibrary:reader'))
            else:
                error = "密码不正确"
        except:
            error = "用户名不存在"

        return render(request, 'booklibrary/reader_login.html', {"error":error})

def readerregister(request):
    if request.method == "GET":
        return render(request,'booklibrary/reader_register.html')
    else:
        try:
            un = request.POST.get("username")
            pwd = request.POST.get("password")
            email = request.POST.get("email")
            StudentUser.objects.create_user(un, password=pwd, is_active = False)
            id = StudentUser.objects.get(username = un).id
            # 序列化id
            serutil = Serializer(settings.SECRET_KEY,300)
            resultid = serutil.dumps({"userid":id}).decode("utf-8")



            # TODO 需要进行序列化加密
            send_mail("点击激活账户", " <a href = 'http://127.0.0.1:8000/booklibrary/active/%s'> 点击我激活账户</a> "%(resultid,),settings.DEFAULT_FROM_EMAIL,[email])

        except Exception as e:
            return render(request, 'booklibrary/reader_register.html', {"error":e})

        return redirect(reverse('booklibrary:readerlogin'))

def reader(request):
    username = request.session.get("username")
    return render(request,'booklibrary/reader.html',{"username":username})




def readerlogout(request):
    request.session.flush()
    return redirect(reverse('booklibrary:readerlogin'))

def readerquery(request):
    if request.method == "GET":
        return render(request,'booklibrary/reader_query.html')
    else:
        error = None
        item = request.POST.get("item")
        query = request.POST.get("query")
        books = None
        if query:
            if item == "author":
                books = Book.objects.filter(author = query)
            else:
                books = Book.objects.filter(name=query)
        else:
            error = "请输入查询内容"

        return render(request, 'booklibrary/reader_query.html',{"books":books,"error":error})

def book(request,id):
    book = get_object_or_404(Book, pk=id)
    reader = History.objects.filter(book_id=id).filter(status =0) .first()
    error = None
    if request.method == "POST":
        if reader:
            error = 'The book has already borrowed.'
        else:
            history = History()
            history.book = book
            history.studentuser = StudentUser.objects.get(username = request.session.get("username"))
            history.date_borrow = datetime.now()
            history.date_return = datetime.now()+timedelta(days=30)
            history.status = False
            history.save()
            return redirect(reverse('booklibrary:book',args=(id,)))

    return render(request, 'booklibrary/reader_book.html', {"book": book, "reader": reader, "error":error})

def readerinfo(request):
    user = get_object_or_404(StudentUser, username = request.session.get("username"))
    return render(request,'booklibrary/reader_info.html',{"user":user})

def readermodify(request):
    error = None
    if request.method == 'POST':
        if not request.POST['username']:
            error = 'You have to input your name'
        else:
            user = StudentUser.objects.get(username = request.session.get("username"))
            user.username = request.POST['username']
            college = request.POST['college']
            user.college = college
            num = request.POST['number']
            if num:
                user.num = num
            email = request.POST['email']
            if email:
                user.email = email
            pwd = request.POST['password']
            if pwd:
                user.set_password(pwd)
            user.save()
            request.session['username'] = user.username
            return redirect(reverse('booklibrary:readerinfo'))
    return render(request,'booklibrary/reader_modify.html',{"error":error})

def readerhistory(request):
    user = get_object_or_404(StudentUser, username = request.session.get("username"))
    histroys = History.objects.filter(studentuser_id = user.id)
    return render(request,'booklibrary/reader_histroy.html',{"histroys":histroys})


def upload(request):
    """
    上传图片
    :param request:
    :return:
    """
    if request.method == "GET":
        return render(request,'booklibrary/reader_upload.html')
    elif request.method == "POST":
        # 文件数据需要使用FILES 获取  enctype = "multipart/form-data"
        hp = HotPic(index = request.POST["index"], pic = request.FILES["pic"])
        hp.save()
        return redirect(reverse('booklibrary:index'))

def edit(request):
    """
    富文本编辑
    :param request:
    :return:
    """
    if request.method == "GET":
        return render(request,'booklibrary/edit.html')
    elif request.method == "POST":
        title = request.POST["title"]
        message = request.POST["message"]
        msg = MessageInfo(title=title,message =message)
        msg.save()
        return redirect(reverse('booklibrary:index'))

def mail(request):
    """发送邮件"""

    try:
        send_mail("Django发送邮件", "Django自带邮件功能，<a src = 'http://127.0.0.1:8000/booklibrary/'> 百度</a> 你可以使用sendmail 或者sendmassmail 发送",
                  settings.DEFAULT_FROM_EMAIL, ["496575233@qq.com", "zhangzhaoyu@qikux.com"]
                  )
        # send_mass_mail((("Django发送邮件1", "Django自带邮件功能，你可以使用sendmail 或者sendmassmail 发送",
        #           settings.DEFAULT_FROM_EMAIL, ["496575233@qq.com", "zhangzhaoyu@qikux.com"]
        #           ),("Django发送邮件2", "Django自带邮件功能，你可以使用sendmail 或者sendmassmail 发送",
        #           settings.DEFAULT_FROM_EMAIL, ["496575233@qq.com", "zhangzhaoyu@qikux.com"]
        #           ),("Django发送邮件3", "Django自带邮件功能，你可以使用sendmail 或者sendmassmail 发送",
        #           settings.DEFAULT_FROM_EMAIL, ["496575233@qq.com", "zhangzhaoyu@qikux.com"]
        #           )))
    except:
        return HttpResponse("发送失败")

    return HttpResponse("发送成功")

def active(request,idstr):
    """
    用户激活用户 id为用户id
    :param request:
    :param id:
    :return:
    """
    deser = Serializer(settings.SECRET_KEY,300)
    try:
        obj = deser.loads(idstr)
        user = StudentUser.objects.get(pk=obj["userid"])
        user.is_active = True
        user.save()
        return redirect(reverse('booklibrary:readerlogin'))
    except SignatureExpired as e:
        return HttpResponse("连接失效")

def ajax(request):
    return render(request,'booklibrary/ajax.html')

def ajaxajax(request):
    if request.method == "GET":
        return HttpResponse("GET请求成功")
    elif request.method == "POST":
        print("hello")
        return HttpResponse("POST请求成功")


def ajaxlogin(request):
    if request.method == "GET":
        return render(request,'booklibrary/ajaxlogin.html')
    elif request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        verifycode = request.POST["verifycode"]
        user = StudentUser.objects.filter(username=username).first()
        if user:
            exits = user.check_password(password)
            if not exits:
                return HttpResponse("登录失败")
            else:
                if verifycode == request.session.get("verifycode"):
                    return HttpResponse("登录成功")
                else:
                    return HttpResponse("验证码错误")
        else:
            return HttpResponse("用户名不存在")



def checkuser(request):
    if request.method == "POST":
        username = request.POST["username"]
        user = StudentUser.objects.filter(username = username).first()
        if user is None:
            return HttpResponse("failed")
        else:
            return HttpResponse("success")

def verifycode(request):
    # 读取验证码图片
    # with open('static/img/verifycode.png', 'rb') as f:
    #     return HttpResponse(f.read())

#     需要生成一张验证码图片   并且保存图片验证码码值

#     定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100),
               random.randrange(20, 100),
               random.randrange(20, 100))
    width = 100
    heigth = 25
    # 创建画面对象
    im = Image.new('RGB', (width, heigth), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, heigth))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    print(rand_str,'+++++++++++++')

demo4/templates/booklibrary/ajax.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ajax</title>

    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>

    <script>
        $(function(){
            $("#load").click(function(){
                $.ajax({
                    url:'/booklibrary/ajaxajax/',
                    type:"post",
                    data:{"csrfmiddlewaretoken": $("input[name=csrfmiddlewaretoken]").val() },
                    success:function(data){
                        console.log(data);
                    }
                })
            })
        })

    </script>
</head>
<body>
    {% csrf_token %}
    <button id="load">点击load内容</button>
    <div id="info"></div>
    <div id="info2"></div>



</body>
</html>

demo4/templates/booklibrary/ajaxlogin.html
{% extends 'booklibrary/base.html' %}
{% block title %}登录{% endblock %}
{% block linkcss %}
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <script>
        $(function(){
            $("#username").blur(function(){
                $.ajax({
                    url:"/booklibrary/checkuser/",
                    type:'post',
                    data:{
                    "csrfmiddlewaretoken":$("input[name=csrfmiddlewaretoken]").val(),
                    "username":$("#username").val()
                    },
                    success:function(data){
                        $("#usernameinfo").text(data);
                    }
                })
            })


            $("#verifycodeimg").click(function(){
                this.src = '/booklibrary/verifycode/'+"?time="+new Date().getTime()
            })
        })

    </script>

{% endblock %}


{% block body %}
<h2>登录</h2>

<form action="{% url 'booklibrary:ajaxlogin' %}" method="post">
    {% csrf_token %}
    用户名： <input type="text" name="username" id="username"> <span id="usernameinfo"></span>
    <br>
    密&nbsp;&nbsp;&nbsp;&nbsp;码： <input type="password" name="password">
    <br>
    <img id="verifycodeimg" src="{% url 'booklibrary:verifycode' %}" alt="验证码加载失败"> <input type="text" name="verifycode">

    <br>
    <input type="submit" value="登录">

</form>

{% endblock %}

demo4/templates/booklibrary/base.html
<!doctype html>
<title> {% block title %} 图书管理系统 {% endblock %} </title>
<link rel=stylesheet type=text/css href="/static/css/style.css">
{% block linkcss %}

{% endblock %}

<!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>





<div class=page>
  <h1>图书管理系统</h1>
  <div class=navigation>
    {% block link %}{% endblock %}
  </div>
  <div class=body>
    {% block body %}{% endblock %}
   </div>
  <div class=footer>
     -- 河南奇酷学院
      <br>
     -- zzy0371
      <br>
     -- 496575233@qq.com
  </div>
</div>
    

demo4/templates/booklibrary/echarts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>显示图表</title>
    <script src="https://www.echartsjs.com/examples/vendors/echarts/echarts.min.js"></script>

</head>
<body>
    <div id="info1" style="width:100%; height:300px">
    </div>
    <div id="info2" style="width:100%; height:300px">
    </div>


    <script>
        var myChart = echarts.init(document.getElementById('info1'));

                var option = {
            title: {
                text: 'ECharts 入门示例'
            },
            tooltip: {},
            legend: {
                data:['销量']
            },
            xAxis: {
                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
            },
            yAxis: {},
            series: [{
                name: '销量',
                type: 'bar',
                data: [5, 20, 36, 10, 10, 20]
            }]
        };

         myChart.setOption(option);



         var myChart2 = echarts.init(document.getElementById('info2'));
         option2 = {
    title: {
        text: '堆叠区域图'
    },
    tooltip : {
        trigger: 'axis',
        axisPointer: {
            type: 'cross',
            label: {
                backgroundColor: '#6a7985'
            }
        }
    },
    legend: {
        data:['邮件营销','联盟广告','视频广告','直接访问','搜索引擎']
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'邮件营销',
            type:'line',
            stack: '总量',
            areaStyle: {},
            data:[120, 132, 101, 134, 90, 230, 210]
        },
        {
            name:'联盟广告',
            type:'line',
            stack: '总量',
            areaStyle: {},
            data:[220, 182, 191, 234, 290, 330, 310]
        },
        {
            name:'视频广告',
            type:'line',
            stack: '总量',
            areaStyle: {},
            data:[150, 232, 201, 154, 190, 330, 410]
        },
        {
            name:'直接访问',
            type:'line',
            stack: '总量',
            areaStyle: {normal: {}},
            data:[320, 332, 301, 334, 390, 330, 320]
        },
        {
            name:'搜索引擎',
            type:'line',
            stack: '总量',
            label: {
                normal: {
                    show: true,
                    position: 'top'
                }
            },
            areaStyle: {normal: {}},
            data:[820, 932, 901, 934, 1290, 1330, 1320]
                }
            ]
        };

         myChart2.setOption(option2);
    </script>
</body>
</html>

demo4/templates/booklibrary/index.html
{% extends 'booklibrary/base.html' %}
{% block title %}
{% load extend_fun %}
{% load cache %}

首页
{% endblock %}

{% block link %}
    <a href="{% url 'booklibrary:readerlogin' %}">读者登录 </a>
{% endblock %}

{% block body %}
    <h2>欢迎使用</h2>
    <div class="hot">
        <hr>
        <h5>热门图书</h5>
        <hr>

        {% cache 500 hot_pic %}
        {% gethot_pics as hot_pics%}
          <!--轮播图-->
          <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            {% for pic in hot_pics %}
                {% if pic.index == 1%}
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                {% else %}
                    <li data-target="#carousel-example-generic" data-slide-to="{{pic.index|add:-1}}"></li>
                {% endif %}
            {% endfor %}
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">

            {% for pic in hot_pics %}
                {% if pic.index == 1%}
                        <div class="item active">
                          <img src="/static/media/{{pic.pic.name}}" alt="...">
                          <div class="carousel-caption">
                            {{pic.pic.name}}
                          </div>
                        </div>
                {% else %}
                   <div class="item">
                      <img src="/static/media/{{pic.pic.name}}" alt="...">
                      <div class="carousel-caption">
                        {{pic.pic.name}}
                      </div>
                    </div>
                {% endif %}
            {% endfor %}
          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
        {% endcache %}
    </div>
    <hr>
    <div class="articles">
        <h5>热门文章</h5>
        <hr>
        {% for message in messageinfos %}
            {{message.message|safe}}

        <hr>
        {% endfor %}

    </div>



{% endblock %}

demo4/templates/booklibrary/reader.html
{% extends 'booklibrary/base.html' %}
{% block title %} 欢迎使用 {% endblock %}
{% block link %} 
	<a href="{% url 'booklibrary:readerlogout' %}"> 注销[{{username}}] </a> |
	<a href="{% url 'booklibrary:readerquery' %}"> 查询 </a> |
	<a href="{% url 'booklibrary:readerinfo' %}"> 查看个人信息 </a> |
	<a href="{% url 'booklibrary:readerhistory'%}"> 查看阅读记录 </a>

{% endblock %}

{% block body %}
	<h2> 欢迎使用 </h2>
{% endblock %}

demo4/templates/booklibrary/reader_info.html
{% extends "booklibrary/base.html" %}
{% block title %} 个人主页 {% endblock %}

{% block link %}
	<a href="{% url 'booklibrary:reader' %}"> 返回  </a>  |
	<a href="{% url 'booklibrary:readermodify' %}"> 修改 </a>
{% endblock %}
{% block body  %}
	<h2> 用户信息 </h2>
	{% if user %}
	<li> 用户名 {{user.username}} </li>
	<li> 学院名 {{user.college}} </li>
	<li> 学号 {{user.num}} </li>
	<li> 邮箱 {{user.email}} </li>
	{% endif %}

{% endblock %}

demo4/templates/booklibrary/reader_login.html
{% extends "booklibrary/base.html" %}
{% block title%} 读者登录 {% endblock%}
{% block link%}
	<a href="{% url 'booklibrary:index' %}"> 返回   </a>|
	<a href="{% url 'booklibrary:readerregister' %}"> 注册 </a>
{% endblock%}


{% block body %}
	<h2> 读者登录 </h2>
	{% if error %}
	<div class = error>
	  <strong>Error : </strong> {{error}}
	</div>
	{% endif %}
	<form action="" method=post>
		{% csrf_token %}
	  <dl>
	    <dt>用户名: </dt>
	    <dd><input type=text name=username size=30> </dd>
	    <dt>密码:	 </dt>
	    <dd><input type=password name=password size=30> </dd>
	  </dl>
	  <div class=actions>
	    <input type=submit value="登录">
	  </div>
	</form>
{% endblock %}

demo4/templates/booklibrary/reader_modify.html
{% extends "booklibrary/base.html" %}
{% block title %} 个人信息修改 {% endblock %}
{% block link %} 
	<a href="#"> 返回 </a>
{% endblock %}
{% block body %}
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
	<form action="{% url 'booklibrary:readermodify' %}" method=post>
		{% csrf_token %}
	  <dl>
	    <dt>用户名:</dt>
	    <dd><input type=text name=username size=30 > </dd>
	    <dt>请输入新密码(不输入就是不修改):</dt>
	    <dd><input type=password name=password size=30> </dd>
	    <dt>学院:</dt>
	    <dd><input type=text name=college size=30 > </dd>
	    <dt>学号:</dt>
	    <dd><input type=text name=number size=30 > </dd>
	    <dt>邮箱:</dt>
	    <dd><input type=text name=email size=30 > </dd>
	  </dl>
	  <div class=actions><input type=submit value="确定"></div>
	</form>

{% endblock %}

demo4/templates/booklibrary/reader_query.html
{% extends "booklibrary/base.html" %}
{% block title %} 查询  {% endblock %}
{% block link %} 
	<a href="{% url 'booklibrary:reader' %}"> 返回 </a>
{% endblock %}
{% block body %}
	<h2> 查询 </h2> 
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
    <div class=actions>
	  <form action="{% url 'booklibrary:readerquery' %}" method="post">
		  {% csrf_token %}
	    <dd>
	      <select name="item">
		<option value="name"> 书名 </option>
		<option value="author"> 作者 </option>
	      </select>
	      <input type="text" name="query" size="80"> 
	      <input type="submit" value="查询">
	    </dd> 
	  </form>
	</div>
	{% if books %}
	<table width="600" border="1" align="center">
	  <tr>
	    <th align="center"> ISBN </th>
	    <th align="center"> 书名 </th>
	    <th align="center"> 作者</th>
	    <th align="center"> 出版商 </th>
	    <th align="center"> 出版时间 </th>	
	    <th align="center"> 查看信息 </th>
	  </tr>
	  {% for book in books %}
	  <tr>
	    <th align="center"> {{book.id}}</th>
	    <th align="center"> {{book.name}} </th>
	    <th align="center"> {{book.author}}</th>
	    <th align="center"> {{book.publish_com}} </th>
	    <th align="center"> {{book.publish_date}}</th>
	    <th align="center"> <a href="{% url 'booklibrary:book' book.id %}"> 点击进入 </a> </th>
	  </tr>
	  {% endfor %}
	  {% endif %}
	</table>	
{% endblock %}

demo4/templates/booklibrary/reader_upload.html
{% extends 'booklibrary/base.html' %}
{% block title %}
<title>上传图片</title>
{% endblock %}

{% block body %}
<form action="{% url 'booklibrary:upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    排序编号： <input type="text" name="index">
    <br>
    选择图片: <input type="file" name="pic">
    <br>
    <input type="submit" value="提交">
</form>
{% endblock %}