demo3/blog/urls.py
from django.conf.urls import url
from . import views
from .feed import PostFeed
app_name = "blog"
urlpatterns = [
    # 进入首页显示
    url(r'^$', views.index, name='index'),
    # 进入文章详情页，需要传入文章id
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    # 点击归档项目，需要传入年份，月份，跳转到首页
    url(r'archives/(\d+)/(\d+)/', views.archives, name='archives'),
    # 点击分类项目，需要传入分类id，跳转到首页
    url(r'category/(\d+)/', views.category, name='category'),
    # 点击标签项目，需要传入标签id，跳转到首页
    url(r'tag/(\d+)/', views.tag, name='tag'),
    url(r'^rss/$', PostFeed(),name='rss'),

]

demo3/comment/urls.py
from django.conf.urls import url
from . import views
app_name = 'comment'
urlpatterns = [
    url(r'^commitcomment/(\d+)/$',views.commitcomment,name='commitcomment')
]

demo3/demo3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
# 使用haystack自带查询视图函数
from haystack.views import SearchView


urlpatterns = [
    path('admin/', admin.site.urls),
    url('blog/',include('blog.urls',namespace='blog')),
    url('blog/',include('comment.urls',namespace='comment')),
    # 全文检索路由
    url('search/',SearchView(),name='search'),
]

demo3/blog/models.py
from django.db import models
# 使用Django自带用户系统
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    """
    文章分类表
        name : 分类命名
    """
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    文章标签表
        name: 标签命名
    """
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    文章表
        title： 标题
        summary： 摘要
        body： 主体
        views： 文章阅读数
        create_time： 文章默认创建时间
        modified_time： 文章最后更改时间
        category： 文章分类，与文章之间为一对多的关系
        tags： 文章标签，与文章之间为多对多关系
        author： 文章作者，使用Django自带用户系统
    """
    title = models.CharField(max_length=20)
    summary = models.CharField(max_length=200,blank=True,null=True)
    body = models.TextField()
    views = models.PositiveIntegerField(default=0)
    create_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def increseview(self):
        self.views += 1
        self.save()

demo3/comment/models.py
from django.db import models
# Create your models here.
from blog.models import Post
class Comment(models.Model):
    """
    评论模型
    name 评论用户名
    email 用户邮件
    url 用户个人主页
    text 评论内容
    create_time 评论时间
    post 文章
    """
    name = models.CharField(max_length=20)
    email = models.EmailField(blank=True,null=True)
    url = models.URLField(blank=True,null=True)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)

demo3/comment/forms.py
from django.forms import ModelForm
from .models import Comment
class CommentForm(ModelForm):
    """
    评论模型对应的表单类
    """
    class Meta():
        model = Comment
        fields = ['name','email','url','text']

demo3/blog/views.py
from django.shortcuts import render,get_object_or_404,get_list_or_404
from django.http import HttpResponse
from .models import Post,Tag,Category
from comment.forms import CommentForm
import markdown
from django.core.paginator import Paginator
# Create your views here.

def getpage(request,objectlist):
    # 分页器
    paginator = Paginator(objectlist,2)
    pagenum = request.GET.get("page")
    pagenum = 1 if pagenum == None else pagenum
    page = paginator.page(pagenum)
    return page

def index(request):
    postlist = Post.objects.all()
    page = getpage(request,postlist)
    context = {
        # "postlist":postlist,
        "page":page,
    }
    return render(request,'blog/index.html',context)

def detail(request,id):
    post = get_object_or_404(Post,pk = id)
    post.increseview()

    # 第一种直接利用markdown生成html
    # post.body = markdown.markdown(post.body, extensions = [
    #     #     'markdown.extensions.extra',
    #     #     'markdown.extensions.codehilite',
    #     #     'markdown.extensions.toc'
    #     # ])

    md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc'
    ])
    post.body = md.convert(post.body)
    post.toc = md.toc

    context = {
        "post":post,
        "form": CommentForm()
    }
    return render(request,'blog/single.html',context)

def archives(request,y,m):
    postlist = get_list_or_404(Post, create_time__year = y, create_time__month = m)
    page = getpage(request,postlist)
    context = {
        # "postlist":postlist,
        "page":page,
    }
    return render(request,'blog/index.html',context)

def category(request,id):
    postlist = get_object_or_404(Category,pk=id).post_set.all()
    page = getpage(request,postlist)
    context = {
        # "postlist":postlist,
        "page":page,
    }
    return render(request,'blog/index.html',context)

def tag(request,id):
    postlist = get_object_or_404(Tag,pk=id).post_set.all()
    page = getpage(request,postlist)
    context = {
        # "postlist":postlist,
        "page":page,
    }
    return render(request,'blog/index.html',context)

demo3/comment/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from django.http import HttpResponse
from .forms import CommentForm
from blog.models import Post
# Create your views here.
def commitcomment(request,id):
    """
    评论后，保存评论刷新页面
    :param request:
    :param id:
    :return:
    """
    post = get_object_or_404(Post,pk = id)
    if request.method == "POST":
        comment = CommentForm(request.POST)
        if comment.is_valid():
            comment = comment.save(commit=False)
            comment.post = post
            comment.save()
            return redirect(reverse('blog:detail',args=(id,)))
        else:
            return HttpResponse("评论失败")
    else:
        return HttpResponse("评论失败")

demo3/templates/blog/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

demo3/templates/blog/base.html
{% load extend_fun %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="/blog/"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="/blog/" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="/blog/" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="/blog/" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="/blog/" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="/search/">
                            <input type="search" placeholder="搜索" required name="q">
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block left %}

                {% endblock %}
            </main>
            <aside class="col-md-4">
                {% block toc %}

                {% endblock %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        {% getlatestposts as latestpost %}
                        {% for post in latestpost %}
                            <li>
                            <a href="{% url 'blog:detail' post.id %}">{{post.title}}</a>
                            </li>
                        {% empty %}
                            <li>没有最新文章</li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% getdatelist as datelist %}
                        {% for date in datelist %}
                            <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{date.year}} 年 {{date.month}} 月</a>
                            </li>
                        {% empty %}
                            <li>没有归档信息</li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>

                        {% getcategorys as categorys %}
                        {% for category in categorys %}
                        <li>
                            <a href="{% url 'blog:category' category.id %}">{{category.name}} <span class="post-count">({{category.post_set.count}})</span></a>
                        </li>
                        {% empty %}
                        <li>没有分类信息</li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% gettags as tags%}
                        {% for tag in tags %}
                       <li>
                            <a href="{% url 'blog:tag' tag.id %}">{{tag.name}}</a>
                        </li>
                        {% empty %}
                        <li>没有标签信息</li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'blog:rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="/static/js/script.js"></script>

</body>
</html>

demo3/templates/blog/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

demo3/templates/blog/index.html
{% extends 'blog/base.html'%}
{% load extend_fun %}

{% block left %}
    {% for post in page.object_list %}
        <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{% url 'blog:detail' post.id %}">{{post.title}}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{post.category.name}}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="2012-11-09T23:15:57+00:00">{{post.create_time}}</time></a></span>
                <span class="post-author"><a href="#">{{post.author.username}}</a></span>
                <span class="comments-link"><a href="#">{{post.comment_set.all.count}}评论</a></span>
                <span class="views-count"><a href="#">{{post.views}}查看</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{post.summary}}</p>
            <div class="read-more cl-effect-14">
                <a href="{% url 'blog:detail' post.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% empty %}
        没有文章信息
    {% endfor %}




    <div class="pagination-simple">
        {% if page.object_list %}
            {% if page.has_previous %}
                <a href="?page={{page.previous_page_number}}">上一页</a>
                <a href="?page={{page.number|add:-1}}">{{page.number|add:-1}}</a>
            {% endif %}
            <span class="current">第 {{page.number}} 页 / 共 {{page.paginator.num_pages}} 页</span>
             {% if page.has_next %}
                 <a href="?page={{page.number|add:1}}">{{page.number|add:1}}</a>
                <a href="?page={{page.next_page_number}}">下一页</a>
            {% endif %}
        {% endif %}
    </div>

    {% comment %}
        <div class="pagination">
                    <ul>
                        <li><a href="">1</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">4</a></li>
                        <li><a href="">5</a></li>
                        <li class="current"><a href="">6</a></li>
                        <li><a href="">7</a></li>
                        <li><a href="">8</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">11</a></li>
                    </ul>
                </div>
    {% endcomment %}
{% endblock %}

demo3/templates/blog/single.html
{% extends 'blog/base.html'%}
{% load extend_fun %}

{% block left %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">{{post.title}}</h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{post.category.name}}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="2012-11-09T23:15:57+00:00">{{post.create_time}}</time></a></span>
                    <span class="post-author"><a href="#">{{post.author.username}}</a></span>
                    <span class="comments-link"><a href="#">{{post.comment_set.all.count}}评论</a></span>
                    <span class="views-count"><a href="#">{{post.views}}查看</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>
                    {{post.body|safe}}
                </p>
            </div>
        </article>


        <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comment:commitcomment' post.id %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="form.name.id_for_label">名字：</label>
                                {{form.name}}

                            </div>
                            <div class="col-md-4">
                                <label for="form.email.id_for_label">邮箱：</label>
                                {{form.email}}

                            </div>
                            <div class="col-md-4">
                                <label for="form.url.id_for_label">网址：</label>
                                {{form.url}}

                            </div>
                            <div class="col-md-12">
                                <label for="form.text.id_for_label">评论：</label>
                                {{form.text}}

                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>


                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{post.comment_set.all.count}}</span> 条评论</h3>

                        <ul class="comment-list list-unstyled">
                            {% for comment in post.comment_set.all %}
                            <li class="comment-item">
                                <span class="nickname">{{comment.name}}</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{comment.create_time}}</time>
                                <div class="text">
                                    {{comment.text}}
                                </div>
                            </li>
                            {% empty %}
                            <li>没有评论信息</li>
                            {% endfor %}
                        </ul>

                    </div>

                </section>

{% endblock %}




{% block toc %}
<div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>

                        {{post.toc|safe}}

                </div>
{% endblock %}

demo3/templates/search/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>搜索结果</title>
</head>
<body>
    {% if query %}
    {% for post in page.object_list %}
        <li>{{post.object.title}}</li>
    {% empty %}
        没有找到内容
    {% endfor %}

    {% endif %}

</body>
</html>