demo1/booktest/urls.py
from django.conf.urls import url
from . import views

app_name = 'booktest'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^list/$',views.list,name='list'),
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    url(r'^delete/(\d+)/$',views.delete,name='delete'),
    url(r'^addhero/(\d+)/$',views.addhero,name='addhero'),
    url(r'^addherohandler/$',views.addherohandler,name='addherohandler')
]

demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('booktest/',include('booktest.urls',namespace='booktest'))
]

"""
项目URL 
通过urlpatterns 列表中的内容将路由和视图绑定
"""


"""
去除硬编码
1， 给应用添加app_name 
2,  在项目url配置文件中 在include中给应用添加命名空间
3， 在应用配置文件中 给url配置 名字
4， 在html中解除硬编码   {% url '命名空间:url名字'  参数  %}

"""

demo1/booktest/models.py
from django.db import models

# Create your models here.

class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.btitle

class HeroInfo(models.Model):
    hname = models.CharField(max_length=20)
    hgender = models.BooleanField()
    hcontent = models.CharField(max_length=50)
    # 外键 第一个参数为表名 第二个参数代表删除类型
    hbook = models.ForeignKey('BookInfo',on_delete=models.CASCADE)
    def __str__(self):
        return self.hname


    def skill(self):
        return self.hcontent

    skill.short_description = '绝招'

    def sex(self):
        return self.hgender
    sex.short_description = '性别'

    def name(self):
        return self.hname

    name.short_description = '姓名'




"""
 django MVT  M
 ORM 对象中O 
 需要定义实体类 
 
 
 定义模型：继承models.Model
 配置数据库：默认sqlite
 将应用名添加到应用列表 installed_apps
 
 
 python manage.py makemigrations 生成迁移文件
 python manage.py migrate 执行迁移

 
"""

"""
python manage.py shell 进入命令：不需要运行项目就可以操作数据库
导入类  from  booktest.models import HeroInfo,BookInfo
查找所有行  表名.objects.all()
根据主键查找 表名.objects.get(pk =1)
添加对象 **.save()
修改    **.save()
删除    **.delete()

一对多： 一方存在主键  多方存在主键也存在外键（一方中主键）

一方.heroinfo_set.all()

类名.objects.create( 列名=值)   不需要save

"""

demo1/booktest/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse,HttpResponseRedirect
from .models import BookInfo,HeroInfo
from django.template import loader
# Create your views here.

# 定义视图函数
def index(request):
    # return HttpResponse("首页")

    # 加载模板
    # indextem = loader.get_template('booktest/index.html')
    # cont = {"username":"zzy"}
    # # 使用变量参数渲染模板
    # result = indextem.render(cont)
    # # 返回模板
    # return HttpResponse(result)

    return render(request,'booktest/index.html',{"username":request.session.get("username")})

def login(request):
    if request.method == "GET":
        return render(request,'booktest/login.html')
    elif request.method == "POST":
        username = request.POST["username"]
        request.session["username"] = username
        return redirect(reverse('booktest:index'))

def logout(request):
    del request.session["username"]
    return redirect(reverse('booktest:index'))



def list(request):
    # return HttpResponse("列表页")
    bl = BookInfo.objects.all()
    return render(request,'booktest/list.html',{"booklist":bl})


def detail(request,id):
    book = BookInfo.objects.get(pk=id)
    return render(request,'booktest/detail.html',{"book":book})


def delete(request,id):
    try:
        BookInfo.objects.get(pk=id).delete()
        bl = BookInfo.objects.all()
        # 使用render没有刷新请求url
        # return render(request, 'booktest/list.html', {"booklist": bl})
        # 重新向服务器发起请求 刷新url
        return HttpResponseRedirect('/booktest/list/',{"booklist": bl})
    except:
        return HttpResponse("删除失败")


def addhero(request, bookid):
    return render(request, 'booktest/addhero.html', {"bookid":bookid})

def addherohandler(request):

    bookid = request.POST["bookid"]
    hname = request.POST["heroname"]
    hgender = request.POST["sex"]
    hcontent = request.POST["herocontent"]
    print(bookid,hname,hgender,hcontent)
    book = BookInfo.objects.get(pk=bookid)
    hero = HeroInfo()
    hero.hname = hname
    hero.hgender = True
    hero.hcontent = hcontent
    hero.hbook = book
    hero.save()
    return HttpResponseRedirect('/booktest/detail/'+str(bookid)+'/',{"book":book})
    # return HttpResponse("添加成功")
"""
视图函数
将函数和路绑定
"""


"""
创建模板文件夹 templates 
配置模板目录  os.path.join(BASEDIR,'templates')
创建项目模板目录，创建模板 

加载模板  temp=loader.get_template()
使用变量渲染模板  result=temp.render({})
返回  HttpResponse(result)



"""

demo1/templates/booktest/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加角色</title>

    <link rel="stylesheet" href="/static/css/main.css">

</head>
<body>
    <div class="container">
        <h2>请输入角色信息：</h2>

        <form action="{% url 'booktest:addherohandler'%}" method="post">
            <input type="hidden" name="bookid" value="{{bookid}}">
            <br>
            英雄名：<input type="text" name="heroname">
            <br>
            性别： <input type="text" name="sex">
            <br>
            绝招： <input type="text" name="herocontent">
            <br>
            <input type="submit" value="添加">

        </form>

    </div>
</body>
</html>

demo1/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
        <h2>书名:{{book.btitle}}</h2>
        <ul>
            {% for hero in book.heroinfo_set.all %}
                <li>{{hero.hname}} ---- {{hero.hcontent}}</li>
            {% empty %}
                <h3>没有角色信息</h3>
            {% endfor %}

        </ul>
        <a href="{% url 'booktest:addhero' book.id %}">添加角色</a>

        <br>
        {# <a href="/booktest/list/">返回列表页</a> #}
        <a href="{% url 'booktest:list' %}">返回列表页</a>
    </div>
</body>
</html>

demo1/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>

    {% load static from staticfiles %}
    {# <link rel="stylesheet" href="/static/css/main.css"> #}

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
        {% if username %}
        <h2>{{username}} ---<a href="{% url 'booktest:logout' %}">退出</a></h2>

        {% else %}
        <a href="{% url 'booktest:login' %}"> 登录</a>
        {% endif %}

        <br>

        {# <img src="/static/img/wsgi.png" alt="加载图片失败" width="1100px"> #}
        <img src="{% static 'img/wsgi.png' %}" alt="加载图片失败" width="1100px">

        {#  超级链接硬编码 #}
        {#<a href="/booktest/list/">进入列表页</a>#}

        {# 去除硬编码 #}
        <a href="{% url 'booktest:list' %}">进入列表页</a>

    </div>
</body>
</html>

demo1/templates/booktest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
        <h1>书籍信息</h1>

        <ul>
            {% for book in booklist %}
            {# <li><a href="/booktest/detail/{{book.id}}/">{{book.btitle}}</a> </li> #}

            {# 去除硬编码 #}
            <li><a href="{% url 'booktest:detail' book.id %}">{{book.btitle}}</a> <a href="{% url 'booktest:delete' book.id %}">删除</a></li>
            {% empty %}
            <h3>没有图书信息</h3>
            {% endfor %}

        </ul>

        <a href="{% url 'booktest:index' %}">返回首页</a>
    </div>
</body>
</html>

demo1/templates/booktest/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>

    <div class="container">
        <form action="{% url 'booktest:login' %}" method="post">
            用户名: <input type="text" name="username">
            <br>
            <input type="submit" value="登录">

        </form>
    </div>
</body>
</html>